extends RefCounted

## Pile Up skill pack C — one of the three that TowerSkillCatalog merges.
##
## Owned by ONE author. Add your three skills here and nowhere else in the
## catalogue: every other pack is somebody else's file, and the merge in
## TowerSkillCatalog is the whole reason nobody has to edit a shared table
## (docs/PROJECT_STATE.md §12 — the lost-edit problem). Each row is:
##
##   "id": {
##       "category": "self" | "opponent",
##       "title":    "SHORT CAPS NAME",
##       "blurb":    "one line: what it does, in the player's words",
##       "script":   preload("res://scripts/tower_skills/YourSkill.gd"),
##       "glyph":    preload("res://sprites/skills/tower_yourid.png"),
##   },
##
## Ids are global — pick ones unlikely to collide with the other packs, and
## the catalogue will shout if they do. `script` must extend TowerSkill (see
## its header for the lifecycle and every hook). `glyph` is a small square
## PNG under sprites/skills/ named tower_<id>.png, generated by
## scripts/dev/make_tower_skill_icons.py from a pixel map you add under
## scripts/dev/tower_icons/ — same placeholder scheme as Don't Crash's icons.
##
## This pack's theme is the tower and the draw: which brick a player gets,
## and what the tower is when they get it. Tailor takes the next brick away
## from the dice; Keystone takes a brick out of the tower on the target's
## clock; Rubble drops one the target never drew onto it, on that same clock.
## None of them freeze a brick or touch its mass, friction or gravity, the
## controls, the descent speed or the camera's zoom — those are the other
## packs' ground.

const SKILLS := {
	"tailor": {
		"category": "self",
		"title": "TAILOR",
		"blurb": "Your NEXT brick is cut to fit the top of the tower — whichever shape fills the gaps best, instead of the one on the card — with a ghost showing where it goes.",
		"script": preload("res://scripts/tower_skills/TailorSkill.gd"),
		"glyph": preload("res://sprites/skills/tower_tailor.png"),
	},
	"keystone": {
		"category": "opponent",
		"title": "KEYSTONE",
		"blurb": "A brick is pulled out from under the top of the tower on their turn — whatever comes down is on them.",
		"script": preload("res://scripts/tower_skills/KeystoneSkill.gd"),
		"glyph": preload("res://sprites/skills/tower_keystone.png"),
	},
	"rubble": {
		"category": "opponent",
		"title": "RUBBLE",
		"blurb": "A stray brick drops onto the tower at the start of their turn, a beat ahead of their own. It costs nothing if it bounces off — whatever it knocks off is on them, and whatever it leaves is theirs to build on.",
		"script": preload("res://scripts/tower_skills/RubbleSkill.gd"),
		"glyph": preload("res://sprites/skills/tower_rubble.png"),
	},
}
