extends RefCounted

## Pile Up skill pack A — one of the three that TowerSkillCatalog merges.
##
## Owned by ONE author. Add your three skills here and nowhere else in the
## catalogue: every other pack is somebody else's file, and the merge in
## TowerSkillCatalog is the whole reason nobody has to edit a shared table
## (docs/PROJECT_STATE.md §12 — the lost-edit problem). Each row is:
##
##   "id": {
##       "category": "self" | "opponent",
##       "title":    "SHORT CAPS NAME",
##       "blurb":    "one line: what it does, in the player's words",
##       "script":   preload("res://scripts/tower_skills/YourSkill.gd"),
##       "glyph":    preload("res://sprites/skills/tower_yourid.png"),
##   },
##
## Ids are global — pick ones unlikely to collide with the other packs, and
## the catalogue will shout if they do. `script` must extend TowerSkill (see
## its header for the lifecycle and every hook). `glyph` is a small square
## PNG under sprites/skills/ named tower_<id>.png, generated by
## scripts/dev/make_tower_skill_icons.py from a pixel map you add under
## scripts/dev/tower_icons/ — same placeholder scheme as Don't Crash's icons.

const SKILLS := {
	# Physics & matter: what a brick is made of and how the tower behaves as
	# stuff. Glue, a quake, stone — each one a different state of matter.
	"cement": {
		"category": "self",
		"title": "CEMENT",
		"blurb": "Your brick sets to whatever it touches. Hang it off the edge — it stays.",
		"script": preload("res://scripts/tower_skills/CementSkill.gd"),
		"glyph": preload("res://sprites/skills/tower_cement.png"),
	},
	"tremor": {
		"category": "opponent",
		"title": "TREMOR",
		"blurb": "The ground shakes on their turn — hardest the instant their brick lands. Whatever is wobbly finds out.",
		"script": preload("res://scripts/tower_skills/TremorSkill.gd"),
		"glyph": preload("res://sprites/skills/tower_tremor.png"),
	},
	"petrify": {
		"category": "self",
		"title": "PETRIFY",
		"blurb": "The tower is stone until your turn ends. Whatever it was going to drop, it drops on the next player's clock.",
		"script": preload("res://scripts/tower_skills/PetrifySkill.gd"),
		"glyph": preload("res://sprites/skills/tower_petrify.png"),
	},
}
