extends RefCounted

## Pile Up skill pack B — one of the three that TowerSkillCatalog merges.
##
## Owned by ONE author. Add your three skills here and nowhere else in the
## catalogue: every other pack is somebody else's file, and the merge in
## TowerSkillCatalog is the whole reason nobody has to edit a shared table
## (docs/PROJECT_STATE.md §12 — the lost-edit problem). Each row is:
##
##   "id": {
##       "category": "self" | "opponent",
##       "title":    "SHORT CAPS NAME",
##       "blurb":    "one line: what it does, in the player's words",
##       "script":   preload("res://scripts/tower_skills/YourSkill.gd"),
##       "glyph":    preload("res://sprites/skills/tower_yourid.png"),
##   },
##
## Ids are global — pick ones unlikely to collide with the other packs, and
## the catalogue will shout if they do. `script` must extend TowerSkill (see
## its header for the lifecycle and every hook). `glyph` is a small square
## PNG under sprites/skills/ named tower_<id>.png, generated by
## scripts/dev/make_tower_skill_icons.py from a pixel map you add under
## scripts/dev/tower_icons/ — same placeholder scheme as Don't Crash's icons.
##
## This pack's theme is the PILOT — the hands and eyes of whoever is flying
## the brick. None of these touches a landed brick, the draw, the brick's
## size or the camera; each is a change to what the player on the clock can
## do or see while their brick is in the air, and each ends with their turn.

const SKILLS := {
	"plumb": {
		"category": "self",
		"title": "PLUMB LINE",
		"blurb": "Your brick falls at half speed with a line to exactly where it will land — any corner over thin air shows red",
		"script": preload("res://scripts/tower_skills/PlumbLineSkill.gd"),
		"glyph": preload("res://sprites/skills/tower_plumb.png"),
	},
	"crosswind": {
		"category": "opponent",
		"title": "CROSSWIND",
		"blurb": "A wind gusts across their next turn, shoving the brick a whole block sideways every gust — and it may turn on them",
		"script": preload("res://scripts/tower_skills/CrosswindSkill.gd"),
		"glyph": preload("res://sprites/skills/tower_crosswind.png"),
	},
	"nightfall": {
		"category": "opponent",
		"title": "NIGHTFALL",
		"blurb": "Their next brick falls in the dark: only a lantern around it, the tower unseen but for flickers, until the last few blocks",
		"script": preload("res://scripts/tower_skills/NightfallSkill.gd"),
		"glyph": preload("res://sprites/skills/tower_nightfall.png"),
	},
}
