extends RefCounted
class_name SkillCatalog

## The one table that says what modular skills exist, which pool each belongs
## to, and what art advertises it on the choice icons.
##
## Adding a skill is: write one file under scripts/skills/ extending
## SkillEffect, add one row here, and add its id to PlayerBoard's SELF_SKILLS
## or OPPONENT_SKILLS. Nothing else in the codebase needs touching — that is
## the whole point of this layer (docs/PROJECT_STATE.md §11 used to list
## three separate edit sites for a new skill, and every one of them was a
## place two people could collide).
##
## Tank Mode, Nitro and the Taxi are NOT in here. They predate this layer and
## are still branches inside PlayerBoard._resolve_skill_choice /
## receive_opponent_skill. The dispatch checks this catalog first and falls
## through to those, so both kinds coexist without either knowing about the
## other.
##
## ART: every `glyph` below is a PLACEHOLDER, generated by
## scripts/dev/make_placeholder_skill_icons.py rather than drawn by hand — no
## image generator was reachable from the session that built these skills.
## Replacing one is a straight file swap: drop the real art at the same path
## under sprites/skills/ and it is picked up with no code change at all.
## docs/SKILL_ART_BRIEF.md holds the per-skill brief (canvas, frames, palette,
## orientation) for generating the real thing.

const SKILLS := {
	"siren": {
		"category": "self",
		"title": "MAKE WAY",
		"script": preload("res://scripts/skills/SirenSkill.gd"),
		"glyph": preload("res://sprites/skills/icon_siren.png"),
	},
	"pitstop": {
		"category": "self",
		"title": "PIT STOP",
		"script": preload("res://scripts/skills/PitStopSkill.gd"),
		"glyph": preload("res://sprites/skills/icon_pitstop.png"),
	},
	"compact": {
		"category": "self",
		"title": "COMPACT",
		"script": preload("res://scripts/skills/CompactSkill.gd"),
		"glyph": preload("res://sprites/skills/icon_compact.png"),
	},
	"roadblock": {
		"category": "opponent",
		"title": "DETOUR",
		"script": preload("res://scripts/skills/RoadblockSkill.gd"),
		"glyph": preload("res://sprites/skills/icon_roadblock.png"),
	},
	"slick": {
		"category": "opponent",
		"title": "OIL SLICK",
		"script": preload("res://scripts/skills/SlickSkill.gd"),
		"glyph": preload("res://sprites/skills/icon_slick.png"),
	},
	"smoke": {
		"category": "opponent",
		"title": "SMOKE SCREEN",
		"script": preload("res://scripts/skills/SmokeScreenSkill.gd"),
		"glyph": preload("res://sprites/skills/icon_smoke.png"),
	},
}

static func has_skill(id: String) -> bool:
	return SKILLS.has(id)

static func category_of(id: String) -> String:
	var entry: Dictionary = SKILLS.get(id, {})
	return entry.get("category", "")

static func title_of(id: String) -> String:
	var entry: Dictionary = SKILLS.get(id, {})
	return entry.get("title", id)

static func glyph_of(id: String) -> Texture2D:
	var entry: Dictionary = SKILLS.get(id, {})
	return entry.get("glyph", null)

# Builds an effect already wired to its board. Returns null for an unknown
# id so a caller can fall through to the pre-catalog skills.
static func make(id: String, board) -> SkillEffect:
	if not SKILLS.has(id):
		return null
	var entry: Dictionary = SKILLS[id]
	var scr: Script = entry["script"]
	var effect: SkillEffect = scr.new()
	effect.setup(board, id)
	return effect
